name: dailycheckin

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install dailycheckin --user
      - name: Config
        env:
          config: ${{ secrets.config }}
        run: |
          curl -o config/config.json $config
      - name: Set proxy
        env:
          config: ${{ secrets.ss_config }}
        run: |
          sudo apt-get install shadowsocks-libev simple-obfs
          sudo -E sh -c 'echo $config|base64 -d > /etc/shadowsocks-libev/config.json'
          sudo sh -c 'echo "\
          [Unit]
          Description=Shadowsocks
          After=network.target
          [Service]
          ExecStart=ss-local -c /etc/shadowsocks-libev/config.json
          Rnestart=on-abort
          [Install]
          WantedBy=multi-user.target\
          ">/etc/systemd/system/shadowsocks.service'
          sudo systemctl daemon-reload
          sudo systemctl start shadowsocks
          sleep 3s
          systemctl status --no-pager shadowsocks
      - name: Run
        run: |
          python -u $HOME/.local/bin/dailycheckin
